// GENERATED by scripts/sync-profile.mjs — do not edit by hand.
// Source of truth: CV/cv-generator/data/personal.yaml (CV v3.26.0)
// Re-run: npm run sync
//
// Phone, date of birth, nationality, gender and referees are intentionally
// NOT here — see the header of scripts/sync-profile.mjs.

export const CV_VERSION = "3.26.0";

export const FACTS = {
  "name": "Sajjad Hossain Talukder",
  "location": "Chattogram, Bangladesh",
  "email": "sajjadhossain.cse35@gmail.com",
  "summary": "Full-stack software engineer building cloud-native backends, AI/LLM-driven automation, and cross-platform applications end to end. ICPC Asia-West finalist and published SDN/NDN networking researcher.",
  "profiles": [
    {
      "label": "Website",
      "url": "https://www.sajjadhossaintalukder.com",
      "display": "sajjadhossaintalukder.com"
    },
    {
      "label": "ORCID",
      "url": "https://orcid.org/0009-0003-6612-0726",
      "display": "ORCID"
    },
    {
      "label": "Google Scholar",
      "url": "https://scholar.google.com/citations?user=3wntH9oAAAAJ",
      "display": "Scholar"
    },
    {
      "label": "LinkedIn",
      "url": "https://www.linkedin.com/in/sajjad-hossain-talukder/",
      "display": "linkedin.com/in/sajjad-hossain-talukder"
    },
    {
      "label": "GitHub",
      "url": "https://github.com/Sajjad-Hossain-Talukder",
      "display": "github.com/Sajjad-Hossain-Talukder"
    },
    {
      "label": "Codeforces",
      "url": "https://codeforces.com/profile/SajjadHuseyn",
      "display": "codeforces.com/profile/SajjadHuseyn"
    },
    {
      "label": "LeetCode",
      "url": "https://leetcode.com/sajjadhuseyn/",
      "display": "leetcode.com/sajjadhuseyn"
    }
  ],
  "education": [
    {
      "degree": "Bachelor of Science in Computer Science & Engineering",
      "institution": "Premier University",
      "location": "Chattogram, Bangladesh",
      "when": "Jan 2019 — Jan 2026",
      "grade": "CGPA: 3.98 / 4.00 (1st rank in batch)",
      "details": []
    }
  ],
  "research": [
    {
      "title": "PDAF — SDN-Assisted Adaptive Forwarding in NDN-MANETs",
      "organization": "Undergraduate thesis · Premier University, Dept. of CSE",
      "when": "2026",
      "details": [
        "First-authored an SDN-assisted forwarding framework for NDN over MANETs — BFS-based node-disjoint route discovery, multi-metric route ranking, and network-wide packet suppression via an extended Dead Nonce List. Evaluated in ndnSIM/ns-3 against CSF, CBILEM and SDN-SRP — packet delivery ratio +25-86%, end-to-end latency -63-96%."
      ]
    },
    {
      "title": "FORCE — Federated ORchestration for Cache Eviction in Mobile NDN",
      "organization": "Joint research with Dr. S. M. A. Iqbal · Premier University, Dept. of CSE",
      "when": "2026 — Present",
      "details": [
        "Building a state-aware cache-eviction meta-policy — a controller-hosted D3QN (double dueling DQN) with Prioritized Experience Replay selects each node's eviction policy from ~21 continuous state features, federated via a global Q-network, driven by a Python/ZeroMQ control plane bridged to ndnSIM."
      ]
    }
  ],
  "publications": [
    {
      "title": "PDAF: Performance-Driven Adaptive Forwarding in SDN-Assisted NDN-MANETs",
      "authors": "S. H. Talukder, S. M. A. Iqbal, E. Barua",
      "venue": "IEEE Transactions on Mobile Computing",
      "year": "2026",
      "status": "published",
      "url": "https://doi.org/10.1109/TMC.2026.3722116"
    },
    {
      "title": "Empowering Bengali Language in Drone Control with Artificial Neural Networks",
      "authors": "S. H. Talukder, N. Rezoana, T. Mahmud, N. Basnin, S. Chowdhury, M. S. Hossain, K. Andersson",
      "venue": "Book chapter in Applied Machine Learning on Sensing Technologies, CRC Press / Taylor & Francis, pp. 81-93",
      "year": "2026",
      "status": "published",
      "url": "https://doi.org/10.1201/9781003506218-6"
    }
  ],
  "experience": [
    {
      "title": "Software Engineer",
      "organization": "Pivotly",
      "location": "Minnesota, USA (Remote)",
      "when": "Nov 2025 — Present",
      "details": [
        "Build AI-powered backend services and agentic LLM workflows that automate high-volume business processes, develop the accompanying web and mobile frontends over REST APIs, and deploy them to production on cloud infrastructure."
      ]
    },
    {
      "title": "Software Engineer",
      "organization": "Silicon Orchard Ltd.",
      "location": "Dhaka, Bangladesh",
      "when": "Sep 2024 — Oct 2025",
      "details": [
        "Built and maintained cross-platform (React Native) and native iOS (Swift) applications for global clients, integrating backend APIs and optimizing performance for reliability on unstable networks."
      ]
    },
    {
      "title": "Software Engineer (iOS)",
      "organization": "Xotech",
      "location": "Chattogram, Bangladesh",
      "when": "Mar 2024 — Sep 2024",
      "details": [
        "Developed AI-based iOS applications (Swift, UIKit) backed by PHP/Laravel REST APIs, managing the full lifecycle through to App Store release."
      ]
    }
  ],
  "projects": [
    {
      "name": "Grade Now — AI Grading Platform for Students",
      "url": "https://gradenowai.com",
      "tags": [
        "Agentic AI",
        "LLM",
        "Node.js",
        "Next.js",
        "PostgreSQL",
        "AWS"
      ],
      "details": [
        "Solely built and deployed an AI platform that grades student answer scripts against AI-generated rubrics through a parallel, multi-stage agentic pipeline, cutting evaluation time and improving consistency."
      ]
    },
    {
      "name": "Connect My Advocate — Legal Aid Platform",
      "url": "https://dev-app.connectmyadvocate.com",
      "tags": [
        "Next.js",
        "Node.js",
        "PostgreSQL",
        "Agora SDK",
        "AWS"
      ],
      "details": [
        "Sole engineer behind the complete system — client web, mobile, and admin apps, plus the AWS infrastructure and PostgreSQL backend — for a legal-aid platform with real-time video consultation."
      ]
    },
    {
      "name": "IELTS Pro BD — Mock IELTS Test Platform",
      "url": "https://ieltsprobd.com",
      "tags": [
        "Next.js",
        "Node.js",
        "PostgreSQL",
        "SSLCommerz"
      ],
      "details": [
        "Architected, shipped, and maintain a live computer-delivered mock-IELTS platform with student management, a flexible test-engine editor, and subscription billing."
      ]
    },
    {
      "name": "SmartWeight — Edge Vision Weighing System",
      "url": "https://github.com/Sajjad-Hossain-Talukder/SmartWeight-RaspberryPi-HX711-based-Digital-Weight-Machine-with-Object-Detection",
      "tags": [
        "Raspberry Pi",
        "Python",
        "OpenCV"
      ],
      "details": [
        "Integrated real-time OpenCV object detection with weight sensors on Raspberry Pi to automate billing and product identification, fully on-device."
      ]
    }
  ],
  "achievements": [
    {
      "category": "Competitive Programming — ICPC",
      "items": [
        "ICPC Asia West Championship Finalist, 2022 (Team PUC Eternals)",
        "ICPC Dhaka Regional — Main Round 52nd (2022), 78th (2023), 93rd (2021); Preliminary 76th of 2481 (2023)"
      ]
    },
    {
      "category": "Competitive Programming — Ratings",
      "items": [
        "Codeforces: Specialist (max rating 1417), 1000+ problems solved",
        "CodeChef: 3-star (max rating 1721); also active on LeetCode, LightOJ and TOPH"
      ]
    },
    {
      "category": "Scholarships",
      "items": [
        "Merit-Based Scholarship, Premier University"
      ]
    }
  ],
  "certifications": [
    {
      "name": "IELTS Academic — Overall Band 7.0 (CEFR C1)",
      "issuer": "British Council / IDP · Listening 7.5, Reading 7.5, Writing 6.5, Speaking 6.0",
      "year": "2026",
      "url": "https://drive.google.com/file/d/1OPEChIZ2MfmypfsTmkHfuWxpivRnBnPP/view",
      "overall": "7.0",
      "cefr": "C1",
      "testDate": "27 July 2026",
      "bands": [
        {
          "skill": "Listening",
          "band": "7.5"
        },
        {
          "skill": "Reading",
          "band": "7.5"
        },
        {
          "skill": "Writing",
          "band": "6.5"
        },
        {
          "skill": "Speaking",
          "band": "6.0"
        }
      ]
    }
  ],
  "skills": [
    {
      "category": "Research & Simulation",
      "items": [
        "ndnSIM",
        "ns-3",
        "Python/ZeroMQ control plane",
        "D3QN + Prioritized Experience Replay",
        "Federated Learning",
        "Named Data Networking",
        "SDN"
      ]
    },
    {
      "category": "Languages",
      "items": [
        "JavaScript/TypeScript",
        "Python",
        "Swift",
        "Go",
        "C++",
        "PHP",
        "SQL"
      ]
    },
    {
      "category": "Cloud & DevOps",
      "items": [
        "AWS",
        "Azure",
        "Docker",
        "CI/CD (GitHub Actions)",
        "PostgreSQL",
        "MySQL",
        "Firebase",
        "Linux"
      ]
    },
    {
      "category": "Frameworks & Backend",
      "items": [
        "Next.js",
        "React",
        "Node.js",
        "React Native",
        "SwiftUI/UIKit",
        "Laravel",
        "RESTful APIs"
      ]
    },
    {
      "category": "AI & Systems",
      "items": [
        "Agentic AI & LLM Integration",
        "AI/ML",
        "OpenCV",
        "Deep Reinforcement Learning (D3QN, PER)"
      ]
    }
  ],
  "organizations": [
    {
      "title": "Manager and Trainer (Competitive Programming)",
      "name": "Premier University Computer Club",
      "url": "https://cse.puc.ac.bd/Home/Content/?Alias=premier-university-computer-club",
      "when": "Jan 2021 — Dec 2023",
      "summary": "Ran data-structures and algorithms bootcamps for competitive-programming teams."
    },
    {
      "title": "Program Secretary",
      "name": "Premier University Robotics Club",
      "url": "https://eee.puc.ac.bd/Home/Content/?Alias=puc-robotics-club",
      "when": "Jan 2022 — Dec 2022",
      "summary": "Ran programming classes for club members and arranged and managed the club's events."
    }
  ],
  "contests": [
    {
      "group": "ICPC & NCPC",
      "note": "",
      "entries": [
        {
          "event": "ICPC Asia West Championship",
          "year": "2022",
          "team": "PUC Eternals",
          "result": "Finalist"
        },
        {
          "event": "ICPC Dhaka Regional — Main Round",
          "year": "2023",
          "team": "PUC Eternals",
          "result": "78th of 224 teams"
        },
        {
          "event": "ICPC Dhaka Regional — Online Preliminary",
          "year": "2023",
          "team": "PUC Eternals",
          "result": "76th of 2481 teams"
        },
        {
          "event": "ICPC Dhaka Regional — Main Round",
          "year": "2022",
          "team": "PUC Eternals",
          "result": "52nd of 162 teams"
        },
        {
          "event": "ICPC Dhaka Regional — Online Preliminary",
          "year": "2022",
          "team": "PUC Eternals",
          "result": "84th of 1648 teams"
        },
        {
          "event": "ICPC Dhaka Regional — Main Round",
          "year": "2021",
          "team": "PUC Eternals",
          "result": "93rd of 165 teams"
        },
        {
          "event": "ICPC Dhaka Regional — Online Preliminary",
          "year": "2021",
          "team": "PUC Eternals",
          "result": "106th of 1747 teams"
        },
        {
          "event": "MIST NCPC",
          "year": "2020",
          "team": "PUC Noob Coders",
          "result": "141st of 162 teams"
        }
      ]
    },
    {
      "group": "Inter University Programming Contest (IUPC)",
      "note": "Numerous IUPC events including BUET IUPC and CUET IUPC, representing PUC Eternals and PUC Gryffindor's.",
      "entries": []
    }
  ],
  "memberships": [
    {
      "role": "Member",
      "name": "IEEE",
      "url": "",
      "when": "2023",
      "summary": "Member of the global professional body for engineering and technology."
    },
    {
      "role": "Member",
      "name": "Rotaract Club of Chattogram Commercial City",
      "url": "",
      "when": "2020 — 2022",
      "summary": "Community-service initiatives and youth-leadership activities."
    }
  ],
  "languages": [
    {
      "name": "Bengali",
      "level": "Native"
    },
    {
      "name": "English",
      "level": "C1 (CEFR) — IELTS Academic, Overall Band 7.0 (Jul 2026)"
    }
  ],
  "interests": [
    "Named Data Networking (NDN) & SDN",
    "Deep & Federated Reinforcement Learning",
    "In-Network Caching and Forwarding",
    "Agentic AI",
    "Quantum Computing"
  ]
} as const;

export type Facts = typeof FACTS;
